### ISSUE TITLE
Slow opening time

### ISSUE THREAD

**Issue by shyim** [Aida-Enna/LGMAConsole#1]
Hey thanks for the Tool,

my Google Drive Folder has 200 nsp files currently, if i add the folder to Tinfoil its loading soooo long. Have you any idea how to increase the performance of that? It looks like Tinfoil opens each file and that is so slow 🙈

**Comment by shyim** [comment]
I have solved it myself by using the nut server :blush:

**Comment by KaitonGX1** [comment]
> I have solved it myself by using the nut server 😊

can you please elaborate for the ill-informed how you managed to solve this Im having the same exact issue of extremely long opening times.

**Comment by shyim** [comment]
My setup is currently: PlexDrive + https://github.com/blawar/nut/

**Comment by Aida-Enna** [comment]
Yeah, this is unfortunately because the Google Drive API limits the number of concurrent requests/max requests you can do in a certain time. I don't think there's really a workaround for it, sorry =/
