### ISSUE TITLE
ftp can show only 100 files

### ISSUE THREAD

**Issue by programista91** [Aida-Enna/LGMAConsole#2]
FTP always shows 100 files, although I have more of them.

**Comment by Aida-Enna** [comment]
Yeah, this is unfortunately because the Google Drive API limits the number of concurrent requests/max requests you can do in a certain time. I don't think there's really a workaround for it, sorry =/

**Comment by programista91** [comment]
Can we redirect DDNS to it? so that people outside my network could access this FTP?

**Comment by Gee19** [comment]
@Aida-Enna seems it is a limitation of FtpServer.

I started working on a PR to increase PageSize to 1000 and add support for paging but I'm not very familiar with the library so this is what I got so far.

https://github.com/FubarDevelopment/FtpServer/pull/60
